version: '3.7'
services:
  znode-mainnet:
    image: rumblefish1337/zcashblockchain:v2.1.2-master
    tty: true
    ports:
      - 8334:8334
    volumes:
      - ./zcash/dockermainnet.conf:/root/.zcash/zcash.conf
    command: bash -c "/znode/zcashd -debug -txexpirydelta=18000 -checklevel=0 -checkblocks=10 -dbcache=500"

  znode-testnet:
    image: rumblefish1337/zcashblockchain:v2.1.1-1-fork
    tty: true
    ports:
      - 8334:8334
    volumes:
      - ./zcash/testnet.conf:/root/.zcash/zcash.conf
    command: bash -c "/znode/zcashd -debug -txexpirydelta=18000 -checklevel=0 -checkblocks=10 -dbcache=500"
    networks:
      vpcbr:
        ipv4_address: 10.3.0.2
    # depends_on:
    #   - tor-socks

  tor-socks:
    container_name: tor-socks
    image: tor-socks
    ports:
      - '9050:9050'
    networks:
      vpcbr:
        ipv4_address: 10.3.0.3

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/16
